#!/bin/bash

client_dir="$1"

if [ "$client_dir" == "" ]; then
  echo "Usage: $0 client_root_dir"
  exit 1
fi

targetdir="$client_dir/code/game-general/Networking/Messages/"
targetdir="$(echo $(cd $(dirname $targetdir); pwd)/$(basename $targetdir))"
thisdir="$(dirname $0)"
cwd="$(pwd)"

namespace="game_general.Networking.Messages"

source "$thisdir/shared"

cd "$thisdir/game"
echo "Exporting to $targetdir"
mkdir -p "$targetdir"
rm -rf "$targetdir"/*.cs
../tools/ProtoGen.exe *.proto -namespace="$namespace" -output_directory="$targetdir" -nest_classes=true
cd "$cwd"

checksum_file="$targetdir/ProtoChecksum.cs"
echo "Writing protocol definition checksums to $checksum_file"
checksum=$(proto_md5 "$thisdir/game/"*.proto)
cat > "$checksum_file" << EOF
// Generated by protos/gen_client.sh
// Do not edit!
namespace $namespace {
  public static class ProtoChecksum {
    public const string CHECKSUM = "$checksum";
  }
}
EOF
