#!/bin/bash

set -e

client_dir="$1"

if [ "$client_dir" == "" ]; then
  echo "Usage: $0 client_root_dir"
  exit 1
fi

thisdir="$(dirname $0)"
source "$thisdir/shared"

game_targetdir=$(abspath "$client_dir/unity/Assets/Code/game-general/Networking/Messages/")
android_targetdir=$(abspath "$client_dir/android-support/src/")

cwd="$(pwd)"
protoc=$(abspath "$thisdir/tools/protoc.exe")
cs_protoc=$(abspath "$thisdir/tools/ProtoGen.exe")

namespace="game_general.Networking.Messages"

cd "$thisdir/game"
echo "Exporting to $game_targetdir"
mkdir -p "$game_targetdir"
rm -rf "$game_targetdir"/*.cs
$cs_protoc *.proto -namespace="$namespace" -output_directory="$game_targetdir" -nest_classes=true
cd "$cwd"

checksum_file="$game_targetdir/ProtoChecksum.cs"
echo "Writing protocol definition checksums to $checksum_file"
checksum=$(proto_md5 "$thisdir/game/"*.proto)
cat > "$checksum_file" << EOF
// Generated by protos/gen_client.sh
// Do not edit!
namespace $namespace {
  public static class ProtoChecksum {
    public const string CHECKSUM = "$checksum";
  }
}
EOF

cd "$thisdir/bg_client"
echo "Exporting to $android_targetdir"
$protoc *.proto --java_out=$android_targetdir
cd "$cwd"
