#!/bin/bash

thisdir="$(cd "$(dirname "$0")"; pwd)"
cwd="$(pwd)"

targetdir="$thisdir/../src/gen/scala/"
targetdir="$(echo $(cd $(dirname $targetdir); pwd)/$(basename $targetdir))"

protoc="$thisdir/tools/protoc.exe"

source "$thisdir/shared"

echo "Exporting to $targetdir."
rm -rf "$targetdir"/*
for dir in game control; do
  cd "$thisdir/$dir"
  echo "Exporting in $dir"
  $protoc "--plugin=protoc-gen-scala=$thisdir/tools/scalapb-0.4.9.exe" \
    *.proto --scala_out="$targetdir"
done
cd "$cwd"

checksum_file="$targetdir/netmsg/ProtoChecksum.scala"
echo "Writing protocol definition checksums to $checksum_file"
checksum=$(proto_md5 "$thisdir/game/"*.proto)
cat > "$checksum_file" << EOF
// Generated by protos/gen_server.sh
// Do not edit!
package netmsg

object ProtoChecksum { val checksum = "$checksum" }
EOF
