package app.persistence

import java.util.UUID

import implicits._

import app.models.User

import DBDriver._
import scala.slick.lifted.Tag

/**
 * Created by arturas on 2015-01-16.
 */
package object tables {
  class Users(tag: Tag) extends Table[(UUID, String, String, Boolean)](tag, "users") {
    def id = column[UUID]("id", O.PrimaryKey, O.DBType("BLOB(16)"))
    def name = column[String]("name")
    def password = column[String]("password")
    def autogenerated = column[Boolean]("autogenerated")

    def idx1 = index("unique_name", name, unique=true)

    def * = (id, name, password, autogenerated)
    def user = (id, name) <> (User.tupled, User.unapply)
  }

  object Tables {
    object users extends TableQuery(new Users(_)) {

    }
  }
}
