create table "users" (
  "id" BLOB(16) PRIMARY KEY NOT NULL,
  "name" VARCHAR(254) NOT NULL,
  "password" VARCHAR(254) NOT NULL,
  "session_token" VARCHAR(254) NOT NULL,
  "autogenerated" INTEGER NOT NULL
);
create unique index "unique_name" on "users" ("name");